# METATUTU Demo Set #2

This demo set is including the tools for Jupyter.

## ðŸ‘‰ Search Path

As METATUTU library developers, if you want to run the demo with source code, please run this **FIRST** to setup the correct search path.

As METATUTU library users, typically you would need to run the demo with the METATUTU library installed on your Python environment with `pip install metatutu`.  If so, please skip the step or even remove the code in below cell.

In [2]:
import sys
import os
METATUTU_PATH = os.path.abspath("../../lib")
if METATUTU_PATH not in sys.path: sys.path.insert(0, METATUTU_PATH)

## ðŸ“˜ metatutu.jupyter.display

### ðŸ“„ Progress - Known total workload

In [3]:
from metatutu.jupyter.display import *

def test_display_progress_1():
    p = ProgressDisplay()
    p.min_interval = 1
    p.text_prefix = "My Task:"
    p.progress_bar_width = "500px"

    task_count = 50000
    p.on_init(task_count)
    for task_index in range(0, task_count):
        p.on_update(task_index + 1)
    p.on_finish()
    
test_display_progress_1()

### ðŸ“„ Progress - Unknown total workload

In [4]:
from metatutu.jupyter.display import *

def test_display_progress_2():
    p = ProgressDisplay()
    p.text_prefix = "My Task:"
    p.show_progress_bar = False

    task_count = 10000
    p.on_init(0)
    for task_index in range(0, task_count):
        p.on_update(task_index + 1)
    p.on_finish()
    
test_display_progress_2()

### ðŸ“„ Bookmark

In [7]:
from metatutu.jupyter.display import *

def test_display_bookmark():
    HTMLDisplay.display_head("ðŸ“Œ Test Result")
    print("some result generated by your code here...")
    
test_display_bookmark()

some result generated by your code here...

### ðŸ“„ Dataframe - Simple display

In [11]:
import numpy as np
import pandas as pd
from metatutu.jupyter.display import *

def test_display_dataframe_1():
    columns = []
    for i in range(0, 10):
        columns.append("column {}".format(i + 1))

    df = pd.DataFrame(np.random.randint(0, 10, (100, 10)), columns=columns)

    HTMLDisplay.display_dataframe(df)
    HTMLDisplay.display_dataframe(df, 5)
    HTMLDisplay.display_dataframe(df, -5)

    
test_display_dataframe_1()

### ðŸ“„ Dataframe - Customized style

In [10]:
import numpy as np
import pandas as pd
from metatutu.jupyter.display import *

def my_formatter(v):
    if v < 3:
        grade = "Low"
    elif v < 6:
        grade = "Medium"
    else:
        grade = "High"
    return "{} ({})".format(v, grade)

def my_styler(styler):
    styler.set_caption("My Table")
    styler.set_sticky(1)
    styler.hide_index()
    styler.format(my_formatter)
    styler.background_gradient(axis=0, vmin=0, vmax=9, cmap="YlGnBu")
    return styler

def test_display_dataframe_2():
    columns = []
    for i in range(0, 10):
        columns.append("column {}".format(i + 1))

    df = pd.DataFrame(np.random.randint(0, 10, (100, 10)), columns=columns)

    HTMLDisplay.display_div(df.style.pipe(my_styler).to_html(), height=200)
    
test_display_dataframe_2()